import './globals.css';
import Navbar from '@components/Navbar/Navbar';
import Footer from '@components/Footer/Footer';

export const metadata = {
  title: 'A simple application demo build on NextJs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <title>Demo App</title>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
